Restore the PLUSHU_USER variable (closes #34)

diff --git a/bin/plushu b/bin/plushu
--- a/bin/plushu
+++ b/bin/plushu
@@ -1,13 +1,46 @@
 #!/usr/bin/env bash
 set -eo pipefail; [[ -n "$PLUSHU_TRACE" ]] && set -x
 
-# If PLUSHU_ROOT is not specially defined, use our home directory
-# (or default to the home directory of the "plushu" user, if running as root)
-if [[ "$EUID" == 0 ]]; then
-  export PLUSHU_ROOT=${PLUSHU_ROOT:-~plushu}
+check_plushu_user () {
+  # let id fail us out if PLUSHU_USER doesn't exist
+  id "$PLUSHU_USER" >/dev/null || exit "$?"
+
+  # If the PLUSHU_ROOT is not explicitly defined
+  if [[ -z "$PLUSHU_ROOT" ]]; then
+    # use PLUSHU_USER's home directory
+    PLUSHU_ROOT=`getent passwd "$PLUSHU_USER" | cut -d: -f6`
+  fi
+}
+
+# If the PLUSHU_USER is not explicitly defined
+if [[ -z "$PLUSHU_USER" ]]; then
+  # If PLUSHU_ROOT is explicitly defined
+  if [[ -n "$PLUSHU_ROOT" ]]; then
+    # Default to the owner of PLUSHU_ROOT
+    PLUSHU_USER=`ls -ld "$PLUSHU_ROOT" | cut -d' ' -f3`
+  # If PLUSHU_ROOT is not explicitly defined
+  else
+    # If the current user is root
+    if [[ "$EUID" == 0 ]]; then
+      # Use whatever user is using sudo, or default to "plushu"
+      PLUSHU_USER=${SUDO_USER:-plushu}
+      check_plushu_user
+    # For any non-root user
+    else
+      # use the current user
+      PLUSHU_USER=`id -un`
+      # use the current user's home as the default PLUSHU_ROOT
+      PLUSHU_ROOT=${PLUSHU_ROOT:-$HOME}
+    fi
+  fi
+# If PLUSHU_USER is explicitly defined
 else
-  export PLUSHU_ROOT=${PLUSHU_ROOT:-$HOME}
+  check_plushu_user
 fi
+
+# Export Plushu's config values to commands and hooks
+export PLUSHU_USER
+export PLUSHU_ROOT
 
 echo_missing_plushurc_msg () {
 cat <<EOF
@@ -38,7 +71,7 @@ if [[ -f "$PLUSHU_ROOT/.plushurc" ]]; then
 else
   echo "No ~/.plushurc found." >&2
   echo >&2
-  if [[ "$USER" == "plushu" ]]; then
+  if [[ "$PLUSHU_USER" == "plushu" ]]; then
     echo_missing_plushurc_msg >&2
   else
     echo_run_as_plushu_msg >&2
