Plugin installation notification tweaks, test fixes

diff --git a/plugins/plugins/subcommands/install b/plugins/plugins/subcommands/install
--- a/plugins/plugins/subcommands/install
+++ b/plugins/plugins/subcommands/install
@@ -2,7 +2,7 @@
 set -eo pipefail
 
 # If a plugin name was specified
-if [ -n $2 ]; then
+if [[ -n $2 ]]; then
 
   case "$2" in
     git:*|ssh:|*@*)
@@ -22,29 +22,35 @@ if [ -n $2 ]; then
   defname=${defname%-plugin}
   target=${3:-$defname}
 
-
-  if [ -e "$PLUSHU_ROOT/plugins/$target" ]; then
-    echo <<EOF
-Plugin "$target" is already installed.
+  # If the plugin already exists
+  if [[ -e "$PLUSHU_ROOT/plugins/$target" ]]; then
+    echo >&2 <<EOF
+Plugin '$target' is already installed.
 Use \`plushu reinstall $target\` to rerun its install script,
 or \`plushu uninstall $target\` first if you want to do a hard reinstall.
 EOF
     exit 1
 
+  # If the plugin isn't already installed
   else
     git clone $remote "$PLUSHU_ROOT/plugins/$target"
 
     # If the newly-cloned plugin has an install script
-    if [ -f "$PLUSHU_ROOT/plugins/$target/install" ]; then
+    if [[ -f "$PLUSHU_ROOT/plugins/$target/install" ]]; then
 
-      # We don't test for executable status, we just let the shell fail if
-      # the install script isn't set executable
+      # We don't test for executable status, we just
+      # let the shell fail if the install script isn't set executable
       "$PLUSHU_ROOT/plugins/$target/install"
+
+    else
+      # Notify that the plugin has been installed
+      # in lieu of a more complex
+      echo "Plugin '$target' installed."
     fi
   fi
 
 # If no plugin name was specified
 else
-  echo "Missing name of plugin to install"
+  echo "Missing name of plugin to install" >&2
   exit 1
 fi
diff --git a/plugins/plugins/subcommands/reinstall b/plugins/plugins/subcommands/reinstall
--- a/plugins/plugins/subcommands/reinstall
+++ b/plugins/plugins/subcommands/reinstall
@@ -2,27 +2,27 @@
 set -eo pipefail
 
 # If a plugin name was specified
-if [ -n $2 ]; then
+if [[ -n $2 ]]; then
 
   # If that plugin exists
-  if [ -d "$PLUSHU_ROOT/plugins/$2"]; then
+  if [[ -d "$PLUSHU_ROOT/plugins/$2" ]]; then
 
     # If that plugin has an install script
-    if [ -f "$PLUSHU_ROOT/plugins/$2/install" ]; then
+    if [[ -f "$PLUSHU_ROOT/plugins/$2/install" ]]; then
 
-      # We don't test for executable status, we just let the shell fail if
-      # the install script isn't set executable
+      # We don't test for executable status, we just
+      # let the shell fail if the install script isn't set executable
       "$PLUSHU_ROOT/plugins/$2/install"
     fi
 
   # If that plugin does not exist
   else
-    echo "Plugin \"$2\" not found"
+    echo "Plugin '$2' not found" >&2
     exit 1
   fi
 
 # If no plugin name was specified
 else
-  echo "Missing name of plugin to reinstall"
+  echo "Missing name of plugin to reinstall" >&2
   exit 1
 fi
