runhook: forward arguments, don't read from terminal

diff --git a/lib/runhook b/lib/runhook
--- a/lib/runhook
+++ b/lib/runhook
@@ -4,15 +4,23 @@ set -eo pipefail
 # For instances where a glob has no matches we want an empty list
 shopt -s nullglob
 
-# Save all of STDIN in the default $REPLY variable
-# (discarding the non-zero exit code for reaching the end-of-file)
-read -rd '' ||:
-
+# Separate the hook name from the extra arguments
 hookname=$1
 shift
 
+# If stdin is a terminal (as it can be when testing runhook)
+if [[ -t 0 ]]; then
+  # Clear the REPLY variable (no input)
+  REPLY=
+# If stdin is not a terminal
+else
+  # Save all of stdin in the default $REPLY variable
+  # (discarding the non-zero exit code for reaching the end-of-file)
+  read -rd '' ||:
+fi
+
 # Run a hook script, if it's executable, with the input from this invocation
-feedhook () {
+exechook () {
   if [[ -f "$1" && -x "$1" ]]; then
     echo -n "$REPLY" | "$@"
   fi
@@ -20,10 +28,13 @@ feedhook () {
 
 # Run all numbered scripts under directories with this hook's name
 run_numbered_hook () {
+  local hookname=$1
+  shift
+
   # Gather every file into an array, prefixing each item with the
   # filename of the script (its position in sort order)
   local filelist=()
-  for hook in $PLUSHU_ROOT/plugins/*/hooks/$1/*; do
+  for hook in $PLUSHU_ROOT/plugins/*/hooks/$hookname/*; do
     filelist+=("${hook##*/} $hook")
   done
 
@@ -35,7 +46,7 @@ run_numbered_hook () {
 
   # Call each script in sorted order
   for hookline in "${filelist[@]}"; do
-    feedhook ${hookline#* }
+    exechook ${hookline#* } "$@"
   done
 }
 
@@ -52,17 +63,17 @@ if [[ -z "$PLUSHU_ROOT" ]]; then
 fi
 
 # Run ordered pre-hooks
-run_numbered_hook pre-$1
+run_numbered_hook pre-$hookname "$@"
 
 # Run other pre-hooks
 for hook in $PLUSHU_ROOT/plugins/*/hooks/pre-$hookname; do
-  feedhook $hook "$@"
+  exechook $hook "$@"
 done
 
 # Run normal hooks
 for hook in $PLUSHU_ROOT/plugins/*/hooks/$hookname; do
-  feedhook $hook "$@"
+  exechook $hook "$@"
 done
 
 # Run ordered (post)hooks
-run_numbered_hook $1
+run_numbered_hook $hookname "$@"
